'use strict'

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      'cards',
      [
        {
          deckID: 3,
          cardName: 'The Fool',
          frontImage: 'https://i.imgur.com/ey993wQ.png',
          frontImageInv: 'https://i.imgur.com/u2fyPvh.png',
          cardArtist: 'Marta Milczarek',
          cardUpDef: 'Beginning, faith, spontaneity, apparent folly',
          cardInvDef:'Holding back, recklessness, risk-taking',
          cardDetails:"The fool is a young woman walking unknowingly toward a cliff. Like the Rider-Waite deck, the fool has a dog, and in this case two! She has a white rose pinned to her clothing to symbolize freedom from baser desires and a bundle tied to her walking stick, representing untapped collective knowledge./nMarta drew the fool as a Lipka Tatar, a culture she doesn’t see depicted in a positive light very much despite having been a significant part of the populace in her motherland (Poland) for centuries. The fool is wearing Sarmatian clothing from the Polish-Lithuanian nobility.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
{
          deckID: 3,
          cardName: 'The Magician',
          frontImage: 'https://i.imgur.com/Iv7JowL.png',
          frontImageInv: 'https://i.imgur.com/8bSxITu.png',
          cardArtist: 'Enrica Eren Angiolini',
          cardUpDef: 'Manifestation, resourcefulness, power, inspired action',
          cardInvDef:'Manipulation, poor planning, untapped talents',
          cardDetails:"A buff woman kneels with one arm raised to the divine, holding a wand and has her index figure pointed up. Her other arm is resting on a sword with her index finger pointing to the ground - the other two minor arcana symbols of a cup and pentacle are in the background with another wand. She has an infinity symbol over her head and an ouroboros belt, symbols of eternity./nEren kept much of the original symbolism but added modern visuals, playing up the fantasy elements of the card.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The High Priestess',
          frontImage: 'https://i.imgur.com/s8eTnXP.png',
          frontImageInv: 'https://i.imgur.com/8iTxh5G.png',
          cardArtist: 'Aadorah',
          cardUpDef: 'Intuition, sacred knowledge, divine feminine,the subconscious mind',
          cardInvDef:'Secrets, disconnected from intuition, withdrawal and silence',
          cardDetails:"A high priestess kneels next to a pond with a crescent moon crown and her eyes closed. She is surrounded by pomegranates and palm leaves, and in the background are the two pillars of Boaz and Jachin. She is meant to have the secrets of the universe in her, and knows what lies beyond the veil of unknowing./nAadorah worked to create a calm scene where the viewer could almost hear the sound of the water and scent of the fruit. She wanted the priestess to have a sense of peaceful wisdom.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The Empress',
          frontImage: 'https://i.imgur.com/Ga5V1dV.png',
          frontImageInv: 'https://i.imgur.com/jqIjY73.png',
          cardArtist: 'Umaimah',
          cardUpDef: 'Femininity, beauty, nature, nurturing, abundance',
          cardInvDef:'Creative block, dependence on others',
          cardDetails:"A powerful woman holds a scepter and wears a crown. Her throne is amidst grasses, representing her rule over the fertile and life giving earth. Her elaborate clothing and jewelry further highlight her power and rule, and her peaceful expression helps to remind the viewer to keep their feet firmly planted on the earth./nUmaimah wanted her pieces to highlight black women in a beautiful light.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The Emperor',
          frontImage: 'https://i.imgur.com/FQ5SMPr.png',
          frontImageInv: 'https://i.imgur.com/4qC4ORy.png',
          cardArtist: 'Celi Godfried',
          cardUpDef: 'Authority, establishment, structure, a father figure',
          cardInvDef:'Domination, excessive control, lack of discipline, inflexibility',
          cardDetails:"A woman sits on a throne adorned with rams and she is calmly confident in her ability to rule everything. She symbolizes the top of an ultimate secular hierarchy and patriarchy, and a need for organization./nCeli found it important to represent a strong and wise Black woman as the Emperor. She was inspired by Kente cloths, a traditional indigenous Ghanian textile that symbolizes pride, knowledge and experience, and included their patterns in the fashion design.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The Hierophant',
          frontImage: 'https://i.imgur.com/PwLpkHq.png',
          frontImageInv: 'https://i.imgur.com/UTNT2oN.png',
          cardArtist: 'Ivy Berces',
          cardUpDef: 'Spiritual wisdom, religious beliefs, conformity, tradition, institutions',
          cardInvDef:'Personal beliefs, freedom, challenging the status quo',
          cardDetails:"The Hierophant has her right hand raised in a blessing, forming a bridge between Heaven and Earth, and holds a triple cross in her left hand. She is seated on a throne between Law and Liberty, or obedience and disobedience./nIvy wanted to make the female version of the Hierophant regal, wise, and magical. She painted the papal tiara as dahlias, symbolizing elegance and dignity in floriography. On the Filipiniana style dress, Ivy added elegant patterns derived from pitch pine, a plant symbolizing wisdom.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The Lovers',
          frontImage: 'https://i.imgur.com/G6v9KxR.png',
          frontImageInv: 'https://i.imgur.com/rrqj9Hi.png',
          cardArtist: 'Mayticks',
          cardUpDef: 'Love, harmony, relationships, values alignment, choices',
          cardInvDef:'Self-love, disharmony, imbalance, misalignment of values',
          cardDetails:"Two figures lay back to back in a bed while naked, showing they have nothing to hide from each other. The apples and snake symbolize the garden of Eden, and twelve lit candles represent the twelve Zodiac signs. Their positioning can indicate both alignment and misalignment, making the card easily read both upright and reversed./nMayticks used much of the original imagery, but added her own take by making it gay and body positive.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The Chariot',
          frontImage: 'https://i.imgur.com/QX6AsB6.png',
          frontImageInv: 'https://i.imgur.com/VNohgLX.png',
          cardArtist: 'Alex Perkins',
          cardUpDef: 'Control, willpower, success, action, determination',
          cardInvDef:'Self discipline, opposition, lack of direction',
          cardDetails:"An armored figure stands in a chariot, holding a wand and wearing a star crown representing celestial influences. She is wearing armor to represent military strengths like discipline and determination to be victorious based on self mastery and willpower. She also represents a healthy ego, not too headstrong or weak to make solid good decisions./nAlex painted the figure’s hands away from any reigns to stress that she is able to charge forward through with only her strength of will. Rather than having the chariot pulled by a sphinx, the chariot has a lion to represent pride - Alex wanted to include that pride can be detrimental to her goals by way of hubris.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Strength',
          frontImage: 'https://i.imgur.com/zxmUw7p.png',
          frontImageInv: 'https://i.imgur.com/x4A9bSc.png',
          cardArtist: 'Mona',
          cardUpDef: 'Courage, focus, and composure',
          cardInvDef:'Inner strength, self-doubt, low energy, raw emotion',
          cardDetails:"A woman holds the jaw of a lion, representing both enlightenment and earthly cravings. She is surrounded by flowers, including her tattoos and crown. Above both figures is an infinity symbol. The calm scene is meant to reflect a calm inner strength rather than physical strength, and compassion in gently guiding the lion’s face./nMona wanted to keep much of the original symbolism and meaning from the Rider-Waite strength card. The flowers represent a variety of meanings, including courage, wisdom, and strength. The figure’s tattoos are based on West African imagery and patterns reflecting strength, as well.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The Hermit',
          frontImage: 'https://i.imgur.com/m0B6cSW.png',
          frontImageInv: 'https://i.imgur.com/jUwOejG.png',
          cardArtist: 'Floh',
          cardUpDef: 'Introspection, Guidance, Solitude',
          cardInvDef:'Isolation, loneliness, withdrawal',
          cardDetails:"A cloaked woman carries a staff in one hand and a bright lantern in the other, walking through harsh wasteland before a mountain range. The hermit represents choosing a life of seclusion for self-reflection, and hardship./nFloh kept the symbolism from the Rider-Waite card, wanting to keep the theme of needed time for a solitary quest to find the answers within.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Wheel of Fortune',
          frontImage: 'https://i.imgur.com/nPihEZI.png',
          frontImageInv: 'https://i.imgur.com/3G99MfF.png',
          cardArtist: 'Indy',
          cardUpDef: 'Luck, karma, destiny',
          cardInvDef:'Bad luck, resistance to change, breaking cycles',
          cardDetails:"The center of the card is the wheel of fortune, representing luck, chance, and life cycles. Two sets of letters are on the wheel - TARO and YHWH, (God of Israel in Hebrew letters). Each of the four corners has an element to reflect the four suits of tarot./nIndy added a lady knight holding the wheel. She is looking to the right while holding her fate in her hands. In reverse, the card works to show her clinging to the wheel and looking to her past, resisting change. Many of the other elements from the original card can be found subtly included in the knight’s cape.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Justice',
          frontImage: 'https://i.imgur.com/myavqcS.png',
          frontImageInv: 'https://i.imgur.com/U5F1L1F.png',
          cardArtist: 'Kukki',
          cardUpDef: 'Fairness, cause and effect',
          cardInvDef:'Unfairness, lack of accountability, dishonesty',
          cardDetails:"Justice stands between two pillars, holding the scales of equality and impartial judgment in one hand, and the sword of decision in the other. Justice is meant to remind us that there is an overall divine balance to the universe./nKukki included black-eyed susans, a flower that traditionally represents justice. She left the meaning of Justice’s amputated arm and open blindfold up to the viewer.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The Hanged Man',
          frontImage: 'https://i.imgur.com/sE1DBLU.png',
          frontImageInv: 'https://i.imgur.com/XGWLLuJ.png',
          cardArtist: 'Bond',
          cardUpDef: 'Pause, surrender, letting go',
          cardInvDef:'Delays, resistance, stalling',
          cardDetails:"A figure is shown hanging from above by their foot and their hands are above their head. A gold halo and their hair surrounds their head. The card both attracts and repulses, representing paradox in the viewer’s own life, controlling by letting go or winning by surrendering./nBond painted the card to capture the overall vibe of stillness, pause, and serenity, rather than focusing on specific visual elements found in the original Rider-Waite card. They wanted this card to feel like floating.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Death',
          frontImage: 'https://i.imgur.com/gC8TYgq.png',
          frontImageInv: 'https://i.imgur.com/jQWXz1o.png',
          cardArtist: 'Lesly Oliveira',
          cardUpDef: 'Endings, change, transformation',
          cardInvDef:'Resistance to change, transformation, transition',
          cardDetails:"Death is shown emerging from water with the traditional scythe of Death on her back. She has a skull painted on her face and an actual skull on her shoulder, reminiscent of armor found in the Rider-Waite card. She holds one hand to her chest, and the other holds a white flower which is shedding petals into the water below, turning to fish. This card rarely has to do with actual death, but usually represents something ending and a fresh beginning./nLesly kept much of the original meaning from the Rider-Waite deck but with a re-imagined figure and more delicate elements.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Temperance',
          frontImage: 'https://i.imgur.com/VdNND91.png',
          frontImageInv: 'https://i.imgur.com/JrkWyTr.png',
          cardArtist: 'Dresden Douglas',
          cardUpDef: 'Balance, moderation, patience, purpose',
          cardInvDef:'Imbalance, excess, self-healing',
          cardDetails:"An angelic figure stands with one foot on the earth and the other dipping into the water. They are pouring water from one cup into another with quiet composure. Their calmness is comforting because they are centered and enjoying flourishing good health./nDresden wanted to create a non-binary angelic figure who could be interpreted as masculine or feminine, or a blend of both. They wanted to include how trans, intersex, and gender variant peoples around the world have historical associations with spirituality, mythicality, and elevated being.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The Devil',
          frontImage: 'https://i.imgur.com/vmOITFT.png',
          frontImageInv: 'https://i.imgur.com/hAVOwiV.png',
          cardArtist: 'Ryleigh T.',
          cardUpDef: 'Shadow self, attachment, addition, restriction',
          cardInvDef:'Independence, revelation, release, reclaiming power',
          cardDetails:"A figure sits on a throne with a goat’s head. One hand is raised and one is lowered in gestures of benediction and capped with light and dark crescent moons Two figures are at their feet with snakes wrapped around their arms. This card can represent being tied down against your will or choosing to stay ignorant./nRyleigh chose to highlight the Rider-Waite card’s symbolism and further explore the darker side of the Devil’s meanings.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The Tower',
          frontImage: 'https://i.imgur.com/bHRpTPB.png',
          frontImageInv: 'https://i.imgur.com/wkNyk0i.png',
          cardArtist: 'Cheryl Young',
          cardUpDef: 'Sudden change, upheaval, chaos, revelation, awakening',
          cardInvDef:'Personal transformation, fear of change, averting disaster',
          cardDetails:"A square tower was struck by lighting, setting it on fire, and people are now falling from the tower. This card traditionally represents a sudden upheaval or reversal in fortune, and can mean a person who is eager to disturb the peace with emotional outbursts and unnecessary drama./nCheryl kept the original visual symbolism from the Rider-Waite deck with added imagery from South-East Asia.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The Star',
          frontImage: 'https://i.imgur.com/CgyJchy.png',
          frontImageInv: 'https://i.imgur.com/O2qTWI5.png',
          cardArtist: 'Harriet',
          cardUpDef: 'Hope, faith, purpose, renewal, spirituality',
          cardInvDef:'Lack of faith, despair, self-trust, disconnection',
          cardDetails:"A naked figure kneels by the edge of a pond, holding two bowls. One pours water back into the pond and the other pours onto the land. A large star is above the figure with seven smaller stars around it. The star can represent the light at the end of the tunnel and hope in the future./nHarriet used the classic Rider-Waite elements of the card, passed through a new lens with colors and compositions that would feel striking in print.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The Moon',
          frontImage: 'https://i.imgur.com/tjiHKLQ.png',
          frontImageInv: 'https://i.imgur.com/WbiYn4N.png',
          cardArtist: 'Mali Ware',
          cardUpDef: 'Illusion, fear, anxiety, subconscious, intuition',
          cardInvDef:'Release of fear, repressed emotion, inner confusion',
          cardDetails:"A figure stands holding one glowing hand up and shadowed by a thin crescent moon. A thicker crescent moon surrounds her head, and a full moon is behind her shoulder. She stands between two dark pillars overlooking a still ocean. This card represents having fears and anxieties, and a promise of anything if one remembers to use their imagination./nMali decided to leave out the animal aspects of the original card, but snuck in the lobster in the figure’s brooch. Even though it’s nearly too small to see in the print version, they really wanted to sneak it in somewhere.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The Sun',
          frontImage: 'https://i.imgur.com/8lWUeEY.png',
          frontImageInv: 'https://i.imgur.com/ZqN1fuq.png',
          cardArtist: 'Lin Romanov',
          cardUpDef: 'Positivity, fun, warmth, success, vitality',
          cardInvDef:'Inner child, feeling down, overly optimistic',
          cardDetails:"A woman stands with her hair resplendent with flowers, and with the background, it looks like the sun. She wears golden armor and holds a sunflower in her many hands. The card represents enlightenment, total confidence in oneself, and unlimited energy and health./nLin kept much of the original symbolism but replaced the masculine elements with feminine, painting a radiant sun goddess.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Judgement',
          frontImage: 'https://i.imgur.com/gaIGysz.png',
          frontImageInv: 'https://i.imgur.com/cvyd4vf.png',
          cardArtist: 'Shews/Elyssa',
          cardUpDef: 'Judgement, rebirth, inner calling, absolution',
          cardInvDef:'Self-doubt, inner critic, ignoring the call',
          cardDetails:"An angel looks down from above, holding her golden trumpet. The card reminds the viewer to weigh all sides before coming to a decision, but the decision needs to be made./nElyssa used some of the original Rider-Waite symbolism but simplified it to highlight the angel herself with an air of judgment.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'The World',
          frontImage: 'https://i.imgur.com/GWUwZZC.png',
          frontImageInv: 'https://i.imgur.com/uZbeV1x.png',
          cardArtist: 'Laura Bennett',
          cardUpDef: 'Completion, integration, accomplishment, travel',
          cardInvDef:'Seeking personal closure, short cuts, delays',
          cardDetails:"A naked figure dances above the earth while holding a staff in each hand, surrounded by a lush green wreath. She represents happiness, contentment, and fulfillment, brought on by a sense that everything in the world is working in harmony./nLaura wanted to keep most of the original symbolism and add her own spin to it, highlighting the figure’s happiness.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Ace of Cups',
          frontImage: 'https://i.imgur.com/J0lPfJS.png',
          frontImageInv: 'https://i.imgur.com/WmYiIx5.png',
          cardArtist: 'Rochelle',
          cardUpDef: 'Love, new relationships, compassion, creativity',
          cardInvDef:'Self-love, intuition, repressed emotions',
          cardDetails:"A woman holds a cup up and water is overflowing to pool around her legs into the ocean. This card traditionally represents the need to connect with people with love or forgiveness. It asks the viewer to trust their feelings and go with their intuition./nRochelle went through many changes with this piece, but found that the developments and a willingness to experiment led to an even better final painting. She knew she wanted to create something fantastical and regal, and emphasize the beauty of Black women with these concepts not normally found in mainstream media.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Ace of Pentacles',
          frontImage: 'https://i.imgur.com/zrfrSGh.png',
          frontImageInv: 'https://i.imgur.com/MQAAhkI.png',
          cardArtist: 'Lena',
          cardUpDef: 'A new financial or career opportunity, manifestation, abundance',
          cardInvDef:'Lost opportunity, lack of planning and foresight',
          cardDetails:"A figure sits with her knees to one side, and she is supporting a pentacle on her back. This card can symbolize the possibility of prosperity or a potential for productivity. It can also indicate that it is time to be centered and secure, not too daring or imaginative./nLena wanted to keep the original symbols with a modern take, including a full figure drawing instead of just a hand.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Ace of Swords',
          frontImage: 'https://i.imgur.com/f0eAmIH.png',
          frontImageInv: 'https://i.imgur.com/Cvc7VrX.png',
          cardArtist: 'Lesly Oliveira',
          cardUpDef: 'Breakthroughs, new ideas, mental clarity, success',
          cardInvDef: 'Inner clarity, re-thinking an idea, clouded judgment',
          cardDetails:"The ace of swords is a figure rising from the clouds with a white sword and crown. Their hair flows upward, matching the clouds below. This card can represent an opportunity for clear understanding in the future. It can also represent a challenge is around the corner, and a reminder to look at the issue objectively and honestly./nLesly wanted to keep the original imagery with an updated figure and a sense of strength.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Ace of Wands',
          frontImage: 'https://i.imgur.com/PNpDHMw.png',
          frontImageInv: 'https://i.imgur.com/3LsLyoa.png',
          cardArtist: 'Mayticks',
          cardUpDef: 'Inspiration, new opportunities, growth, potential',
          cardInvDef:'An emerging idea, lack of direction, distractions, delays',
          cardDetails:"A figure sleeps in the fetal position under an archway, with a mountain peak behind them. There is a flowering wand at their feet and a golden chain flowing all around them. This ace represents a seed of possibility in creativity, the beginning of an idea./nMayticks created a figure in the middle in the fetal position, adding to the original symbolism of the beginnings of an idea but with a whole person, not just a hand.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Eight of Cups',
          frontImage: 'https://i.imgur.com/InIssix.png',
          frontImageInv: 'https://i.imgur.com/vSbkTcA.png',
          cardArtist: 'Jess Bernadette',
          cardUpDef: 'Disappointment, abandonment, withdrawal, escapism',
          cardInvDef:'Trying one more time, indecision, aimless drifting, walking away',
          cardDetails:"A figure stands water, three cups grasped to their chest, one in their hand pouring into the water below, and four more cups floating away. The night sky shines above a forest. Traditionally, the card can represent the need to focus on a deep personal truth, letting go of what is not serving the viewer, and lagging energy. It can symbolize the need to realize that it is time to move on./nJess wanted to explore the dual meanings found in the upright and reversed cards. She strongly wanted to feature a nonbinary person with both masculine and feminine attributes brought together in a beautiful card.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Eight of Pentacles',
          frontImage: 'https://i.imgur.com/Sk3hkG3.png',
          frontImageInv: 'https://i.imgur.com/LBQ0CVe.png',
          cardArtist: 'Marta Milczarek',
          cardUpDef: 'Apprenticeship, repetitive tasks, mastery, skill development',
          cardInvDef:'Self-development, perfectionism, misdirected activity',
          cardDetails:"A woman is carving a pentacle with one at her feet and six over her head. Her clothing is delicately embroidered with shapes resembling pentacles too. Traditionally this card reflects a time with heavy focus and invigorating work, leading to great results. This card can also represent enjoying learning new skills, or the need to be careful to check all the details./nMarta wanted to honor her late grandma and her family, born in Belarus but had to flee during WWII. This card features a woman wearing clothing inspired by Belarusian traditional wear.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Eight of Swords',
          frontImage: 'https://i.imgur.com/BOpVUu7.png',
          frontImageInv: 'https://i.imgur.com/uItN7bn.png',
          cardArtist: 'Ryleigh T.',
          cardUpDef: 'Negative thoughts, self-imposed restriction, imprisonment, victim mentality',
          cardInvDef:'Self-limiting beliefs, inner critic, releasing negative thoughts, open to new perspectives',
          cardDetails:"A figure kneels in water, blindfolded and hands bound in front of them. Eight swords are stabbed into the ground around them. The stormy night sky illuminates a castle on a hill behind the figure. This card can represent being bound by restrictions, impossible situations, or troubled relationships. It can also be a reminder that there are always choices that can lead to freedom if one is willing to put in the hard work./nRyleigh kept the original visual symbolism and created a darker mood to heighten the feeling of imprisonment.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Eight of Wands',
          frontImage: 'https://i.imgur.com/vbZO8sm.png',
          frontImageInv: 'https://i.imgur.com/xG3b7HR.png',
          cardArtist: 'Monarobot',
          cardUpDef: 'Movement, fast paced change, action, alignment, air travel',
          cardInvDef:'Delays, frustration, resisting change, internal alignment',
          cardDetails:"Representing making a move, the eight wands fly through the air at a high speed. This card can represent that it is go-time - things are already in quick motion or are about to be. It can also symbolize the arrival of news or information, and bringing things to a close./nMonarobot drew from Maya carvings for her work. The “T” symbols are a representation of wind, and the woman is based on pre-Hispanic creation stories and is made of maize.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Five of Cups',
          frontImage: 'https://i.imgur.com/UneVJet.png',
          frontImageInv: 'https://i.imgur.com/SgDSWuL.png',
          cardArtist: 'Harriet',
          cardUpDef: 'Regret, failure, disappointment, pessimism',
          cardInvDef:'Personal setbacks, self-forgiveness, moving on',
          cardDetails:"A figure in black cloak looks at three knocked over cups at their feet. Two cups stand upright behind them, but they don’t notice as they are too focused on the empty cups. A path leads off into the distance where a castle sits on a mountain top. This card traditionally can represent a loss or setback, but reminds the viewer that possibilities for growth can be initiated from the loss./nHarriet used the classic Rider-Waite elements of the card, passed through a new lens with colors and compositions that would feel striking in print.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Five of Pentacles',
          frontImage: 'https://i.imgur.com/Vh7lo8O.png',
          frontImageInv: 'https://i.imgur.com/vtg4Ymq.png',
          cardArtist: 'Alyssa',
          cardUpDef: 'Financial loss, poverty, loss mindset, isolation, worry',
          cardInvDef:'Recovery from financial loss, spiritual poverty',
          cardDetails:"A woman pulls her cape close around her, tears falling down her face. Behind her, a church window glows with light and warmth, with five stained glass pentacles at the top. The figure doesn’t see the possible warmth and safety because her head is turned away. Traditionally this card can represent poor health, poverty, or rejection. The glow of the church behind the figure can also symbolize a need to reconnect with a spiritual side when suffering./nAlyssa simplified the visuals of the card to make more of an impact with a single figure.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Five of Swords',
          frontImage: 'https://i.imgur.com/JjXCD95.png',
          frontImageInv: 'https://i.imgur.com/bMOVCJF.png',
          cardArtist: 'Bond',
          cardUpDef: 'Conflict, disagreements, competition, defeat, winning at all costs',
          cardInvDef:'Reconciliation, making amends, past resentment',
          cardDetails:"A figure kneels to pick up a sword, while holding two bloody swords in their other hand. Two figures in the distance are walking away from two other swords on the ground. This card can serve a reminder that self-interest, while important, needs to be expanded to be how the self relates to the world. It can also symbolize a need to put self interests first for a minute, especially if being taken advantage of./nBond kept the original visuals, creating a moody and dark piece. The atmosphere was inspired by the classic Rider Waite card, but Bond changed the posture of the foreground figure to emphasize a “winning at any cost” vibe. The swords the figure is holding are the only ones with blood, implying that even though they are walking away from the confrontation, the lasting effects won’t be so easily forgotten.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Five of Wands',
          frontImage: 'https://i.imgur.com/UY6BAkl.png',
          frontImageInv: 'https://i.imgur.com/QORV0kI.png',
          cardArtist: 'Grey Havens',
          cardUpDef: 'Conflict, disagreements, competition, tension, diversity',
          cardInvDef:'Inner conflict, conflict avoidance, tension release',
          cardDetails:"Five people brandish wands, all crossed over each other as if in a fight. This card traditionally represents that Monday feeling - everything seems to go wrong and minor hassles are preventing things from running smoothly. This can also represent competition which can be useful for pushing things to go better when in the right circumstances./nGrey went into this with angels in mind, subverting the traditional Western view of them and the Rider-Waite interpretation of the card. The card features 5 of Grey’s original characters, diverse in gender, sexuality, and body type, but highlights the strife that occurs even within the marginalized LGBT+ community.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Four of Cups',
          frontImage: 'https://i.imgur.com/VKldtLK.png',
          frontImageInv: 'https://i.imgur.com/jYGjBWB.png',
          cardArtist: 'Alyssa',
          cardUpDef: 'Meditation, contemplation, apathy, reevaluation',
          cardInvDef:'Retreat, withdrawal, checking in for alignment',
          cardDetails:"A young person sits under a tree, deep in contemplation/meditation. She is so engrossed in their thoughts that she doesn’t seem to notice the cup above her head, let alone the three already at her feet. Traditionally this card can symbolize self-absorption and an apathy toward noticing anything outside internal struggles. This card can mean being emotionally stuck and a need to reevaluate what is going on inside./nAlyssa kept the original symbolism from the Rider-Waite card and added a more peaceful and modern spin.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Four of Pentacles',
          frontImage: 'https://i.imgur.com/UZ39azm.png',
          frontImageInv: 'https://i.imgur.com/FCawpud.png',
          cardArtist: 'Joanna',
          cardUpDef: 'Saving money, security, conservatism, scarcity, control',
          cardInvDef:'Overspending, greed, self-protection',
          cardDetails:"A knight stands by a bench with four pentacles held close to their body, their cape wrapped around themselves and pentacles. This card represents ownership, control, and possessiveness. This card reminds the viewer to resist holding too tightly onto control as it can stifle creativity or the flow of things./nJoanna wanted to keep much of the original symbolism, and they worked to keep a symmetrical, stable composition since the card can be associated with conservatism and security.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Four of Swords',
          frontImage: 'https://i.imgur.com/KqGOaQ6.png',
          frontImageInv: 'https://i.imgur.com/8WFcQ9m.png',
          cardArtist: 'Hayley Olivia',
          cardUpDef: 'Rest, relaxation, meditation, contemplation, recuperation',
          cardInvDef:'Exhaustion, burn-out, deep contemplation, stagnation',
          cardDetails:"A knight lays on a tomb under a stained glass window portraying a woman and child. Their hands are clasped in prayer, and three swords hang overhead. The fourth sword is under the knight, laying parallel with them. This card can symbolize the need to slow down, take a break, and heal. It is a reminder that it can be a challenge to have a quiet moment but it is vital for health and balance./nHayley wanted to show the calm after the storm. She imagined this knight as being a part of the autism spectrum, and the knight was enjoying the serenity she feels at the end of a day in her own quiet space. This knight is able to find herself in an area of reflection of those who love and support her as she is.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Four of Wands',
          frontImage: 'https://i.imgur.com/VU0PiLK.png',
          frontImageInv: 'https://i.imgur.com/mkoJAQv.png',
          cardArtist: 'Ivy Berces',
          cardUpDef: 'Celebration, joy, harmony, relaxation, homecoming',
          cardInvDef:'Personal celebration, inner harmony, conflict with others, transition',
          cardDetails:"Four wands surround two women dancing joyfully among them. The women have flower wreaths in their hair and are holding flowers. Traditionally, this card represents the joy of living, exciting events, and exhilarating freedom./nIvy wanted to celebrate sapphic love with this card, and this card is based on her good friends, a lesbian couple. Wisteria hangs above the wands, representing love and sensuality, and hydrangeas are in the foreground, symbolizing understanding.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'King of Cups',
          frontImage: 'https://i.imgur.com/ms7IxLc.png',
          frontImageInv: 'https://i.imgur.com/p5KZ1KE.png',
          cardArtist: 'Zoe',
          cardUpDef: 'Emotionally balanced, compassionate, diplomatic',
          cardInvDef:'Self-compassion, inner feelings, moodiness, emotionally manipulative',
          cardDetails:"The king sits on a large throne, with a great golden cape. They hold a cup in one hand and a scepter in the other. The ocean churns around them and crashes over the throne. A ship sits on the horizon and a fish jumps from the ocean behind the throne. This card represents compassion and calm, and additionally asks the viewer to use diplomacy and not force./nZoe kept true to the original symbolism of the card, but added water to tie in the element attached to the suit of cups.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'King of Pentacles',
          frontImage: 'https://i.imgur.com/eH0IDKy.png',
          frontImageInv: 'https://i.imgur.com/Dgvi1Sc.png',
          cardArtist: 'Mali Ware',
          cardUpDef: 'Wealth, business, leadership, security, discipline, abundance',
          cardInvDef:'Financially inept, obsessed with wealth and status, stubborn',
          cardDetails:"A king sits on her wooden throne with carved bulls. Her hands hold a scepter and a pentacle. She is wearing lush green robes and headscarf, adorned with golden elements. This king is responsible, enterprising, and generous. This king card can ask the viewer to examine life to see what kind of actions need to happen - learning a new skill, fixing something broken, or keeping a commitment./nMali really wanted to highlight the lush overgrown sense from the original card, using rich greens and golds to reflect the plants and pentacle throughout the piece.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'King of Swords',
          frontImage: 'https://i.imgur.com/zvIowuY.png',
          frontImageInv: 'https://i.imgur.com/huveZeT.png',
          cardArtist: 'Fiona',
          cardUpDef: 'Mental clarity, intellectual power, authority, truth',
          cardInvDef:'Quiet power, inner truth, misuse of power, manipulation',
          cardDetails: "A king sits in her butterfly shaped throne, wearing bright blue and purple fabrics and silver armor. There is a green landscape at her feet and blue sky behind her throne. She represents a master of logic and reason, cutting through confusion to provide clarity. This card can symbolize the need to tell the truth or judge fairly, or represent someone in the viewer’s life who would act as she would./nFiona added air alchemy signs to tie in the element associated with the suit of swords, and included the air sign zodiac symbols (Gemini, Libra, and Aquarius) in the king’s clothing. The angel depicted in the original card has been morphed here into a full angel on the king’s armor and wings as her crown.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'King of Wands',
          frontImage: 'https://i.imgur.com/lmXj4Ab.png',
          frontImageInv: 'https://i.imgur.com/PzOwaLg.png',
          cardArtist: 'Hayley Olivia',
          cardUpDef: 'Natural-born leader, vision, entrepreneur, honor',
          cardInvDef:'Impulsiveness, haste, ruthless, high expectations',
          cardDetails: "The king sits on her throne which has carvings of salamanders (representing fire and transformation) and holds a blossoming wand in her hand. Traditionally this card radiates positive energy, asking one to jump in and create the good results wanted. This king is charismatic and inspiring./nHayley kept the original symbolism and added more. This character identifies as a woman despite standing against the Western definition of femininity. She is a carpenter, builder, thinker, mathematician. She had to fight to be accepted in all her fields of expertise, and her persistence is her greatest strength.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Knight of Cups',
          frontImage: 'https://i.imgur.com/hrfb89m.png',
          frontImageInv: 'https://i.imgur.com/Aqlk7uQ.png',
          cardArtist: 'Laura R',
          cardUpDef: 'Creativity, romance, charm, imagination, beauty',
          cardInvDef:'Overactive imagination, unrealistic, jealous, moody',
          cardDetails: "The knight of cups rides a horse and holds an overflowing cup in their hand. Their tunic is patterned with fish and the ocean is behind them. This card is a lover of romance and imagination, and can ask the viewer to balance their feelings if too exuberant or unrealistic./nLaura was inspired by romance novel covers for this painting, and painted the knight with dramatic flowing hair, bright colors, and in front of a fading sunset. She wanted to convey the romance, creativity, and imagination this card symbolizes.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Knight of Pentacles',
          frontImage: 'https://i.imgur.com/6znEizg.png',
          frontImageInv: 'https://i.imgur.com/8i7UPYi.png',
          cardArtist: 'Ryleigh T.',
          cardUpDef: 'Hard work, productivity, routine, conservatism',
          cardInvDef: 'Self-discipline, boredom, feeling ‘stuck’, perfectionism',
          cardDetails: "A knight holds a pentacle up to examine it while sitting on their black horse. In the background there is a freshly plowed field. This knight is not afraid of hard work and can be very careful with their methods and money, but this also means they might not have a great sense of humor. This card can ask the viewer to examine their life and see if they are balanced between being grounded but not too stuck./nRyleigh liked working with the original imagery but with a bit of a Viking spin.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Knight of Swords',
          frontImage: 'https://i.imgur.com/W669hQk.png',
          frontImageInv: 'https://i.imgur.com/JiWXPLw.png',
          cardArtist: 'Harriet',
          cardUpDef: 'Ambitious, action-oriented, driven to succeed, fast-thinking',
          cardInvDef: 'Restless, unfocused, impulsive, burn-out',
          cardDetails: "A knight charges forward on a white horse, sword held in front of them. They are wearing armor and a red cape, and a strong wind blows through the whole card. This card can represent logic, but sometimes to the point of tactlessness and rudeness. It can also symbolize the need to balance that energy, or insert some clear headed energy if the situation is too murky./nHarriet used the classic Rider-Waite elements of the card, passed through a new lens with colors and compositions that would feel striking in print.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Knight of Wands',
          frontImage: 'https://i.imgur.com/WuIZGMx.png',
          frontImageInv: 'https://i.imgur.com/BzRr7wF.png',
          cardArtist: 'Enrica Eren Angiolini',
          cardUpDef: 'Energy, passion, inspired action, adventure, impulsiveness',
          cardInvDef: 'Passion project, haste, scattered energy, delays, frustration',
          cardDetails: "The knight sits on their chestnut horse with armor and a helmet, covered in salamanders which are associated with fire and transformation. Their bare chest shows top surgery scars and a muscular build, and they are holding a wand with a glowing orb at the end. This card traditionally represents self-confidence and passion, but can also suggest a need to check to make sure confidence isn’t cockiness./nEren included the salamanders on the armor from the original card, also symbolizing the physical process of transitioning, accompanying the top surgery scars on the chest. The energy sprouting from the wand has the yellow, purple, white, and black colors of the non-binary flag to bring the piece together.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Nine of Cups',
          frontImage: 'https://i.imgur.com/iim3L9j.png',
          frontImageInv: 'https://i.imgur.com/qE9Ut8Z.png',
          cardArtist: 'Alex Perkins',
          cardUpDef: 'Contentment, satisfaction, gratitude, wish come true',
          cardInvDef: 'Inner happiness, materialism, dissatisfaction, indulgence',
          cardDetails: "A figure sits on a bench, arms folded around herself with a look of contentment on her face. Nine cups are above her and are pouring down on and around her. This card is a sign of delight, an encouragement to seek pleasure and contentment in how things are going. There is also a quiet warning to not let pleasure take off without some consideration of future consequences./nAlex wanted their figure to be wrapped in a self-hug, a self soothing gesture of comfort and contentment. The cups are pouring their contents, i.e. her cups runneth over.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Nine of Pentacles',
          frontImage: 'https://i.imgur.com/cSbWeZ7.png',
          frontImageInv: 'https://i.imgur.com/7xEjMhw.png',
          cardArtist: 'Ivy Berces',
          cardUpDef: 'Abundance, luxury, self-sufficiency, financial independence',
          cardInvDef: 'Self-worth, over-investment in work, hustling',
          cardDetails: "A well dressed woman stands in a lush garden, rich with fruit, flowers, and nine pentacles. There is a falcon on her shoulder. This card can symbolize a wish to enjoy the finer things in life, and sign that discipline and self control can in the end provide more opportunities to have finer things. Additionally, this can represent a need to be more self-reliant./nIvy wanted to emphasize the abundance and luxury of the original card. She created the card with the golden hour in mind, and included (on top of traditional grapes) shrubs, apples, a cornucopia, and fine glasses.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Nine of Swords',
          frontImage: 'https://i.imgur.com/KcaamK7.png',
          frontImageInv: 'https://i.imgur.com/MumPVdp.png',
          cardArtist: '',
          cardUpDef: 'Anxiety, worry, fear, depression, nightmares',
          cardInvDef: 'Inner turmoil, deep-seated fears, secrets, releasing worry',
          cardDetails: "A figure lays submerged in water with nine red swords hovering above them. They have a pained expression and are reaching toward one of the swords. This card represents the inner pain generated within, like letting fears and doubts take over or worrying. It can also highlight the would of, should of, could of guilt of indecision, and serve as a reminder to make the best choices for the trouble ahead./nJax deviated a bit from the original card concept to have the figure submerged in water as opposed to waking in a bed. They like the connection to the murkiness (and at times complete darkness) of the unconscious mind during dreaming, or being caught in anxiety-inducing thought patterns. Jax also wanted a self-sabotage element in this card and painted the figure to reach for one of the swords, bringing it closer.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Nine of Wands',
          frontImage: 'https://i.imgur.com/fsV1rq5.png',
          frontImageInv: 'https://i.imgur.com/oJqsSfL.png',
          cardArtist: 'Calli Pryor',
          cardUpDef: 'Resilience, courage, persistence, test of faith, boundaries',
          cardInvDef:'Inner resources, struggle, overwhelm, defensive, paranoia',
          cardDetails: "A warrior stands among 8 wands and holds the 9th in their hand. They are covered in battle wounds but still standing strong. This card can symbolize the need to move forward but carefully. It can also represent stamina and the inner drive to keep going after many setbacks./nCalli stuck close to the original Rider-Waite card symbolism, but added their own spin and changed the wands to be all different kinds.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Page of Cups',
          frontImage: 'https://i.imgur.com/maMQu1L.png',
          frontImageInv: 'https://i.imgur.com/8j6Xh7N.png',
          cardArtist: 'Laura R',
          cardUpDef: 'Creative opportunities, intuitive messages, curiosity, possibility',
          cardInvDef: 'New ideas, doubting intuition, creative blocks, emotional immaturity',
          cardDetails: "The page stands on the shore with a wavy sea behind them. She is looking at the cup in her hand with a bright green fish in it. This card can represent an incoming opening for love and emotion. It can also be a reminder to express and feel feelings with abandon./nLaura wanted to include the aura of inspiration and possibility in this card with the dawn of a new day just beginning to crest over the waves. This is meant to represent the moment of coming to realize an exciting new idea.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Page of Pentacles',
          frontImage: 'https://i.imgur.com/WZUQZrM.png',
          frontImageInv: 'https://i.imgur.com/eg7YOCl.png',
          cardArtist: 'Aubri McEachern',
          cardUpDef: 'Manifestation, financial opportunity, skill development',
          cardInvDef: 'Lack of progress, procrastination, learn from failure',
          cardDetails: "A young person holds a shining pentacle up while standing in a lush green field with flowers, and a mountain range in the distance. The page represents opportunities for wealth and security. The card asks the viewer to act on these chances for success, or can symbolize that life is full of physical enjoyment and not to be afraid to act on those choices either./nAubri wanted to keep the original feel of the card but with an updated take on the figure.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Page of Swords',
          frontImage: 'https://i.imgur.com/mgiPDhF.png',
          frontImageInv: 'https://i.imgur.com/1d4rgxy.png',
          cardArtist: 'Alex C',
          cardUpDef: 'New ideas, curiosity, thirst for knowledge, new ways of communicating',
          cardInvDef: 'Self-expression, all talk and no action, haphazard action, haste',
          cardDetails: "A figure stands holding a sword pointed to the sky. A breeze blows around them and over the green landscape and blue sky. Traditionally, this card can represent an incoming challenge that can lead to personal growth. It can also symbolize a child or child-like adult who has a troubled relationship with the viewer./nAlex took the card meaning quite literally, depicting the page aesthetic with the typical haircut and outfit. She also inserted the triangular spirals sign on the outfit to further support the inconsistent element of the card, which is air.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Page of Wands',
          frontImage: 'https://i.imgur.com/Dm9py1d.png',
          frontImageInv: 'https://i.imgur.com/rEvasMH.png',
          cardArtist: 'Joanna',
          cardUpDef: 'Inspiration, ideas, discovery, limitless potential, free spirit',
          cardInvDef: 'Newly-formed ideas, redirecting energy, self-limiting beliefs, a spiritual path',
          cardDetails: "A young figure inspects the wand in their hands. They are standing in a barren landscape backed with the night sky. They have a wrap around their waist embroidered with salamanders which are associated with fire and transformation. Traditionally, the card represents that something is about to come up that will provide a chance to be creative./nJoanna kept the original symbolism of the card, keeping the figure confident and an overall theme of adventure.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Queen of Cups',
          frontImage: 'https://i.imgur.com/IwiTN6p.png',
          frontImageInv: 'https://i.imgur.com/MwTG1gc.png',
          cardArtist: 'Helen Mask',
          cardUpDef: 'Compassionate, caring, emotionally stable, intuitive, in flow',
          cardInvDef: 'Inner feelings, self-care, self-love, co-dependency',
          cardDetails: "The queen of cups floats in the ocean, holding an ornate cup and pitcher. This cup unlike the others in the suit is a closed cup. Her ocean is calm and she projects an air of calmness. This card asks the viewer to contemplate their feelings to see if they are open to love and tenderhearted feelings. It can also ask if the viewer is in tune with their spirituality and open to how others are doing./nHelen stayed close to the original visual symbolism but added the element of an underwater realm. Because of this, the queen is not seated in a throne but rather floating, calmly watching over her ocean kingdom.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Queen of Pentacles',
          frontImage: 'https://i.imgur.com/wTL1qfX.png',
          frontImageInv: 'https://i.imgur.com/7ltoZeV.png',
          cardArtist: 'Jawsum',
          cardUpDef: 'Nurturing, practical, providing financially, a working parent',
          cardInvDef: 'Financial independence, self-care, work-home conflict',
          cardDetails: "A queen sits on her throne, holding a giant golden pentacle, with a young woman at her feet with rabbit ears. This queen is serene, generous with her time, and nurturing in her home. This card can represent a need to examine life to ensure truthfulness and compassion./nJaws simplified the imagery from the original card to better highlight the queen, and had fun changing the traditionally depicted rabbit on the Rider-Waite card with a young woman here.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Queen of Swords',
          frontImage: 'https://i.imgur.com/SQzGVpw.png',
          frontImageInv: 'https://i.imgur.com/bsjwBpk.png',
          cardArtist: 'Lin Romanov',
          cardUpDef: 'Independent, unbiased judgment, clear boundaries,direct communication',
          cardInvDef:'Overly-emotional, easily influenced, bitchy, cold-hearted',
          cardDetails: "A queen stands, wearing armor and holding a massive sword. Red roses are everywhere, and her clothing has roses embroidered into it. This card asks the viewer to be honest with themselves, to use direct communication. This queen is uninterested in lies or silly games - her commitment is to being truthful.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Queen of Wands',
          frontImage: 'https://i.imgur.com/7zJ8a2R.png',
          frontImageInv: 'https://i.imgur.com/w14tauL.png',
          cardArtist: 'Shews/Elyssa',
          cardUpDef: 'Courage, confidence, independence, social butterfly, determination',
          cardInvDef: 'Self-respect, self-confidence, introverted, re-establish sense of self',
          cardDetails: "The queen sits on her throne with two lions facing opposite directions behind her. She holds a wand above her head with her left hand. Her clothing and the background have sunflowers. A black cat has wrapped herself around the queen’s leg. Traditionally the queen is easygoing and beautiful, confident but not arrogant./nElyssa kept to the original symbolism, creating a queen who is self-assured and attractive.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Seven of Cups',
          frontImage: 'https://i.imgur.com/0tvPB67.png',
          frontImageInv: 'https://i.imgur.com/Ydhajfz.png',
          cardArtist: 'Enrica Eren Angiolini',
          cardUpDef: 'Opportunities, choices, wishful thinking, illusion',
          cardInvDef: 'Alignment, personal values, overwhelmed by choices',
          cardDetails: "A person dances below seven cups, each with a different gift or curse. This card can represent wishful thinking, pondering many different options, or falling into neglect or indulgence if not considered. It can be a reminder to enjoy dreaming but remember to back up the ideas with hard work and plans./nEren stuck to the original symbolism, and transformed the figure to a gorgeous Black woman.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Seven of Pentacles',
          frontImage: 'https://i.imgur.com/hNaxccR.png',
          frontImageInv: 'https://i.imgur.com/fUFEyhT.png',
          cardArtist: 'Helen Mask',
          cardUpDef: 'Long-term view, sustainable results, perseverance, investment',
          cardInvDef: 'Lack of long-term vision, limited success or reward',
          cardDetails: "A woman waters five pentacles in her lush garden, two more pentacles harvested and in her backpack. Her garden is exploding with life. This card is a time out from well deserved success, a moment to breathe and look back at everything accomplished. It can also be a call to reflect and make sure everything is on track for good results./nHelen wanted to paint the gardener without an exhausted expression, but rather stoically tending to her hard earned crop, as the summer days draw to an end.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Seven of Swords',
          frontImage: 'https://i.imgur.com/4W8g74y.png',
          frontImageInv: 'https://i.imgur.com/amBay7H.png',
          cardArtist: 'Jawsum',
          cardUpDef: 'Betrayal, deception, getting away with something, acting strategically',
          cardInvDef: 'Impostor syndrome, self-deceit, keeping secrets',
          cardDetails: "A buff woman holds seven swords to her chest, walking away from something with a pleased expression. Traditionally, this card can represent a feeling of self-satisfaction, a sign of wanting to be a successful lone-wolf, or sneaking/running away from something like obligations or wrong choices./nJaws kept the original symbolism from the card with their own spin on the figure and a variety of swords.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Seven of Wands',
          frontImage: 'https://i.imgur.com/SzNdKGz.png',
          frontImageInv: 'https://i.imgur.com/qZb820f.png',
          cardArtist: 'Alex C',
          cardUpDef: 'Challenge, competition, protection, perseverance',
          cardInvDef: 'Exhaustion, giving up, overwhelmed',
          cardDetails: "A woman stands defensively in the middle of the card, holding a wand while six more point in from outside at her face. She appears calm but determined. This card represents taking a stand, strong convictions, and resistance. It can also be a reminder to see if the battle is truly worth fighting or is it time to turn back./nAlex was inspired by the image of a shaman and the card’s energy of strong convictions with the figure’s defensive posture.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Six of Cups',
          frontImage: 'https://i.imgur.com/aiGP1HR.png',
          frontImageInv: 'https://i.imgur.com/F688bpe.png',
          cardArtist: 'Mayticks',
          cardUpDef: 'Revisiting the past, childhood memories, innocence, joy',
          cardInvDef: 'Living in the past, forgiveness, lacking playfulness',
          cardDetails: "Two figures are sharing wine, three cups in their hands and another three at the dancing figure’s feet. The figures are simply having a good time, playful and carefree. Traditionally, this card reminds the viewer to focus on goodwill and encourages them to be kind, generous, and forgiving./nMayticks wanted to keep the original Rider-Waite card’s mood but with some happy gay twists.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Six of Pentacles',
          frontImage: 'https://i.imgur.com/qsYKVUr.png',
          frontImageInv: 'https://i.imgur.com/41ezcr5.png',
          cardArtist: 'Lin Romanov',
          cardUpDef: 'Giving, receiving, sharing wealth, generosity, charity',
          cardInvDef: 'Self-care, unpaid debts, one-sided charity',
          cardDetails: "A well dressed woman is dumping six pentacles and jewels from a golden container, standing in a rich and lush garden. This card can represent both the haves and the have-nots by considering both the woman dumping her excess of money and jewels to the ground, and the people who might come by to pick them up. It also asks the viewer to ask what it means to be in the middle of these two extremes./nLin worked with her own style to create a new take on the visual symbolism.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Six of Swords',
          frontImage: 'https://i.imgur.com/vp4Wev4.png',
          frontImageInv: 'https://i.imgur.com/imGv6bJ.png',
          cardArtist: 'Mona',
          cardUpDef: 'Transition, change, rite of passage, releasing baggage',
          cardInvDef: 'Personal transition, resistance to change, unfinished business',
          cardDetails: "A figure poles a boat forward with six swords which appear to be stabbed into the boat. This card can represent a listless state where nothing is really wrong, but nothing is really right either. It can symbolize surviving and not thriving, or a recovery period after a big setback. Overall it suggests moving toward something positive overall./nMonarobot drew from Maya carvings for her work. In particular, the swords are represented by a Mesoamerican weapon.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Six of Wands',
          frontImage: 'https://i.imgur.com/80kRNne.png',
          frontImageInv: 'https://i.imgur.com/WETuw9J.png',
          cardArtist: 'Kukki',
          cardUpDef: 'Success, public recognition, progress, self-confidence',
          cardInvDef: 'Private achievement, personal definition of success, fall from grace, egotism',
          cardDetails: "A queen places a laurel wreath onto a kneeling knight while two people watch from the background holding wands with laurel wreaths as well. This card represents the feeling of triumph after working hard toward a goal and it’s nearly complete. It can also symbolize a healthy amount of self esteem with the reminder to check it hasn’t become superiority./nKukki stayed close to the original Rider-Waite symbolism but changed it up a little to show more people than just the original figure on a horse.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Ten of Cups',
          frontImage: 'https://i.imgur.com/qiIISXh.png',
          frontImageInv: 'https://i.imgur.com/msaM6p6.png',
          cardArtist: 'Dresden Douglas',
          cardUpDef: 'Divine love, blissful relationships, harmony, alignment',
          cardInvDef: 'Disconnection, misaligned values, struggling relationships',
          cardDetails: "A couple - two women - have their arms wrapped around each other while a child looks on with a dog. Everyone clearly loves each other, and a rainbow shines and ends on their house. Ten rainbow cups hang in the air over the rainbow. This card represents absolute joy, peace and serenity, and a time of abundant blessings. If there is disharmony in the viewer’s family, this card can suggest the need to figure out the path to reconciliation./nDresden loved painting this and wanted to capture all the love this family has for one another.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Ten of Pentacles',
          frontImage: 'https://i.imgur.com/xc8TFv4.png',
          frontImageInv: 'https://i.imgur.com/D5hI5Nu.png',
          cardArtist: 'Cheryl Young',
          cardUpDef: 'Wealth, financial security, family, long-term success, contribution',
          cardInvDef: 'The dark side of wealth, financial failure or loss',
          cardDetails: "In a courtyard of a castle, an older figure with a heavily embroidered shoulder cloth watches over a younger couple and their child, and two cattle. This figure is the head figure of the family and they are enjoying their successful life. This can represent prosperity and material success, or following convention and tried-and-true methods to do well. This card can also symbolize the need to remember to plan out for the long term and not lose sight of the end goal./nCheryl included a traditional Indonesian shoulder cloth on the main figure in the painting, choosing to highlight nine of the pentacles in the embroidery.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Ten of Swords',
          frontImage: 'https://i.imgur.com/y1cK1pe.png',
          frontImageInv: 'https://i.imgur.com/n9BD8BJ.png',
          cardArtist: 'Grey Havens',
          cardUpDef: 'Painful endings, deep wounds, betrayal, loss, crisis',
          cardInvDef: 'Recovery, regeneration, resisting an inevitable end',
          cardDetails: "A figure is lying face-down on the ground, reaching toward the light. Ten swords are stabbed through their back. Dawn breaks on the horizon. This card represents misfortune, but exaggerated. It suggests that the problem is already at rock bottom, and it’s time to turn the corner to better things. The card can also be a reminder not to be a martyr, but rather to check the mood and start looking up./nGrey was inspired by classic horror movies and pulp cover art to give this a violent, yet sultry feel. They’re just out of reach from the campfire that sheds its warmth on them, a bittersweet reminder of hope despite how close they are to death. The blue cape represents clearer skies which are nowhere to be found in this scene.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Ten of Wands',
          frontImage: 'https://i.imgur.com/bsMWIaY.png',
          frontImageInv: 'https://i.imgur.com/77aNbq7.png',
          cardArtist: 'Floh',
          cardUpDef: 'Burden, extra responsibility, hard work, completion',
          cardInvDef: 'Doing it all, carrying the burden, delegation, release',
          cardDetails: "A figure kneels on the ground, trying to keep her grip on her bundle of ten wands. She is weighed down by her burden of trying to keep them upright. This card can be a reminder to cut back and reduce the workload, or step forward and take on the bulk of the work and responsibility. Overall, the card can mean that life is about to get a little harder for a while, and feel like a fight uphill./nFloh kept to the original meaning of the Rider-Waite card, and used a limited color palette to highlight the warm tones of the figure.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Three of Cups',
          frontImage: 'https://i.imgur.com/LVRGgr6.png',
          frontImageInv: 'https://i.imgur.com/Ofcho82.png',
          cardArtist: 'Jax',
          cardUpDef: 'Celebration, friendship, creativity, collaborations',
          cardInvDef: 'Independence, alone time, hardcore partying, ‘three’s a crowd’',
          cardDetails: "Three young people are dancing in a circle, toasting the cups with joy and a celebratory energy. Flowers are in a circle around their feet, symbolizing the goodness in life and within their little group. One figure has visible top surgery scars, and two figures have flowers in their hair. This card represents a group of people coming together into a community, nurturing the social bonds among them. Additionally, the card can represent reaching out for help like counseling./nJax kept close to the original card, but added their own interpretation of the group to be much more inclusive.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Three of Pentacles',
          frontImage: 'https://i.imgur.com/jnGiaZ2.png',
          frontImageInv: 'https://i.imgur.com/oETrKtv.png',
          cardArtist: 'Aubri McEachern',
          cardUpDef: 'Teamwork, collaboration, learning, implementation',
          cardInvDef: 'Disharmony, misalignment, working alone',
          cardDetails: "Two architects are examining blueprints while another person is painting a pillar that has three pentacles on it. Traditionally, this card is one of group work, indicating the need to work cooperatively toward a common goal. This card can also suggest a need to plan and prepare before moving forward./nAubri was excited to work with this card and add their own modern spin.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Three of Swords',
          frontImage: 'https://i.imgur.com/gv8rYl4.png',
          frontImageInv: 'https://i.imgur.com/3SiTKaO.png',
          cardArtist: 'Mali Ware',
          cardUpDef: 'Heartbreak, emotional pain, sorrow, grief, hurt',
          cardInvDef: 'Negative self-talk, releasing pain, optimism, forgiveness',
          cardDetails: "A figure hovers in midair with three swords stabbing through her heart. Dark stormy clouds frame her with a bright light in the middle. This card represents heartbreak, open wounds, and other painful setbacks in life. It can also be a reminder that everyone is capable of cruelty and to contemplate choices to avoid hurting others./nKeeping close to the original visuals, Mali enjoyed using red details to reflect the red heart of the original card.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Three of Wands',
          frontImage: 'https://i.imgur.com/FWdUgOp.png',
          frontImageInv: 'https://i.imgur.com/Nq1xly2.png',
          cardArtist: 'Umaimah',
          cardUpDef: 'Progress, expansion, foresight, overseas opportunities',
          cardInvDef: 'Playing small, lack of foresight, unexpected delays',
          cardDetails: "A woman stands among three wands in a garden and she is reaching out to touch one. This card traditionally represents looking into the future, examining the long game to figure out how to best get there. It can mean taking risks while being well informed./nUmaimah wanted her pieces to highlight Black women in a beautiful light.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Two of Cups',
          frontImage: 'https://i.imgur.com/e5IhucZ.png',
          frontImageInv: 'https://i.imgur.com/u7UClmR.png',
          cardArtist: 'Anna V.',
          cardUpDef: 'Unified love, partnership, mutual attraction',
          cardInvDef: 'Self-love, break-ups, disharmony, distrust',
          cardDetails: "Two young people exchange cups, symbolizing pledging their love to each other. The Caduceus of Hermes is tattooed on the Sea’s arm, symbolizing commerce, trade, and exchange. A lion’s head is tattooed on the Sky’s arm, symbolizing passion and fiery sexual energy. This card can represent the bonding of two people, groups, ideas, or talents, and signifies that now is not the time to separate but rather reconcile./nBecause this card is considered a positive card associated with romance, Anna wanted to create a card that communicated a pleasant, romantic feeling whether upright or reversed. The connection between the Moon and the Sea represents a deep, true relationship.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Two of Pentacles',
          frontImage: 'https://i.imgur.com/2NCHnje.png',
          frontImageInv: 'https://i.imgur.com/NhKV9VM.png',
          cardArtist: 'Shews/Elyssa',
          cardUpDef: 'Multiple priorities, time management, prioritization, adaptability',
          cardInvDef: 'Over-committed, disorganization, re-prioritization',
          cardDetails: "A young woman holds two balls with pentacles on them and she is dressed as an old school juggler. The two balls are connected with a red ribbon in a loose infinity symbol. This card is a reminder to believe in oneself, that juggling all demands is possible. It can symbolize being graceful and effective at the same time./nShews wanted to highlight the juggling aspect and use an old-school juggler outfit and still include the ribbon between the pentacles.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Two of Swords',
          frontImage: 'https://i.imgur.com/Z6TsnJv.png',
          frontImageInv: 'https://i.imgur.com/owwzzHG.png',
          cardArtist: 'Izzy',
          cardUpDef: 'Difficult decisions, weighing up options, an impasse, avoidance',
          cardInvDef: 'Indecision, confusion, information overload, stalemate',
          cardDetails: "A figure sits on a stone bench with swords in their crossed arms. They are wearing a blindfold and embroidered tunic. A crescent moon sits in an otherwise dark sky, with a dark sea below and mountains on the horizon. This card can represent a tendency to block off emotions without dealing with them, a closed heart, and a reluctance to accept a truth./nIzzy wanted to keep the original imagery with an updated figure.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
	{
          deckID: 3,
          cardName: 'Two of Wands',
          frontImage: 'https://i.imgur.com/XALP9Ko.png',
          frontImageInv: 'https://i.imgur.com/qlSZXI2.png',
          cardArtist: 'Aero',
          cardUpDef: 'Future planning, progress, decisions, discovery',
          cardInvDef: 'Personal goals, inner alignment, fear of unknown, lack of planning',
          cardDetails: "A woman stands on a beach, holding an hourglass while overlooking two wands with orbs. Her head is haloed with a golden circle and the night sky is filled with stars. This card can represent personal power, an invigorating energy that can be used to accomplish great things when wielded thoughtfully./nAero changed what the figure is holding - traditionally it was a globe, but Aero wanted to highlight the tension between contemplating opportunity but needing a push of courage to make progress. The orbs have labradorite and moonstone, representing clarity and intuitive knowledge. Finally, the background has synastry to pull everything together with a sense of the stars aligning.",
          createdAt: new Date(),
          updatedAt: new Date()
        },
  {
          deckID: 2,
          cardName: 'The Fool',
          frontImage: 'https://i.imgur.com/HGfEAdc.jpg',
          frontImageInv: 'https://i.imgur.com/tKhBOHQ.jpg',
          cardArtist: 'Emi Brady',
          cardUpDef: 'Beginnings, innocence, spontaneity, a free spirit',
          cardInvDef: 'Holding back, recklessness, risk-taking',
          cardDetails: '',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          deckID: 2,
          cardName: 'The High Priestess',
          frontImage: 'https://i.imgur.com/lnlTuzy.jpg',
          frontImageInv: 'https://i.imgur.com/JKiSczd.jpg',
          cardArtist: 'Emi Brady',
          cardUpDef: '',
          cardInvDef: '',
          cardDetails: '',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          deckID: 2,
          cardName: 'The Magician',
          frontImage: 'https://i.imgur.com/FD1hPqW.jpg',
          frontImageInv: 'https://i.imgur.com/D9tcLUa.jpg',
          cardArtist: 'Emi Brady',
          cardUpDef: '',
          cardInvDef: '',
          cardDetails: '',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          deckID: 2,
          cardName: 'Wheel of Fortune',
          frontImage: 'https://i.imgur.com/HRJYzth.jpg',
          frontImageInv: 'https://i.imgur.com/626Ya9G.jpg',
          cardArtist: 'Emi Brady',
          cardUpDef: '',
          cardInvDef: '',
          cardDetails: '',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          deckID: 2,
          cardName: 'Justice',
          frontImage: 'https://i.imgur.com/5f1gsvl.jpg',
          frontImageInv: 'https://i.imgur.com/sCaJfuB.jpg',
          cardArtist: 'Emi Brady',
          cardUpDef: '',
          cardInvDef: '',
          cardDetails: '',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          deckID: 2,
          cardName: 'The Empress',
          frontImage: 'https://i.imgur.com/7BeBCcb.jpg',
          frontImageInv: 'https://i.imgur.com/uMPXTdu.jpg',
          cardArtist: 'Emi Brady',
          cardUpDef: '',
          cardInvDef: '',
          cardDetails: '',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          deckID: 2,
          cardName: 'The Emperor',
          frontImage: 'https://i.imgur.com/mVjITRh.jpg',
          frontImageInv: 'https://i.imgur.com/VZ8ZE7A.jpg',
          cardArtist: 'Emi Brady',
          cardUpDef: '',
          cardInvDef: '',
          cardDetails: '',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          deckID: 2,
          cardName: 'The Hierophant',
          frontImage: 'https://i.imgur.com/7I3uD0u.jpg',
          frontImageInv: 'https://i.imgur.com/MYDgL9i.jpg',
          cardArtist: 'Emi Brady',
          cardUpDef: '',
          cardInvDef: '',
          cardDetails: '',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          deckID: 2,
          cardName: 'The Lovers',
          frontImage: 'https://i.imgur.com/JE0TSTw.jpg',
          frontImageInv: 'https://i.imgur.com/Cg77upC.jpg',
          cardArtist: 'Emi Brady',
          cardUpDef: '',
          cardInvDef: '',
          cardDetails: '',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          deckID: 2,
          cardName: 'The Chariot',
          frontImage: 'https://i.imgur.com/TXUyPUI.jpg',
          frontImageInv: 'https://i.imgur.com/DN6Eh4M.jpg',
          cardArtist: 'Emi Brady',
          cardUpDef: '',
          cardInvDef: '',
          cardDetails: '',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          deckID: 2,
          cardName: 'Strength',
          frontImage: 'https://i.imgur.com/xnLNrba.jpg',
          frontImageInv: 'https://i.imgur.com/M2pvUmZ.jpg',
          cardArtist: 'Emi Brady',
          cardUpDef: '',
          cardInvDef: '',
          cardDetails: '',
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          deckID: 2,
          cardName: 'The Hermit',
          frontImage: 'https://i.imgur.com/G5iP8oB.jpg',
          frontImageInv: 'https://i.imgur.com/nEugJ1V.jpg',
          cardArtist: 'Emi Brady',
          cardUpDef: '',
          cardInvDef: '',
          cardDetails: '',
          createdAt: new Date(),
          updatedAt: new Date()
        }
      ],
      {}
    )
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('cards', null, {})
  }
}